# Generated by Django 3.0.1 on 2019-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('discount', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
