# Generated by Django 3.0.1 on 2019-12-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mfr', models.CharField(max_length=300)),
                ('category', models.IntegerField(choices=[(1, 'Food'), (2, 'Drink'), (3, 'Fruit'), (4, 'Daily Supply'), (5, 'Electronic')], default=1)),
                ('bprice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sprice', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
