# Generated by Django 3.0.1 on 2019-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_buy', models.FloatField()),
                ('total_sell', models.FloatField()),
            ],
        ),
    ]
